language: java
sudo: required
dist: trusty
cache:
  directories:
    - $HOME/.m2/repository

matrix:
  fast_finish: true
  include:
    - jdk: openjdk7
    - jdk: oraclejdk8

script:
  - mvn -e package -V
