language: java
sudo: required
dist: trusty
cache:
  directories:
    - $HOME/.m2/repository

os:
  - linux
  - osx

matrix:
  include:
    - os: linux
      jdk:
        - openjdk7
        - openjdk8
        - openjdk11
        - oraclejdk8
        - oraclejdk11
  allow_failures:
    - os: osx
      osx_image: xcode10.1
      jdk: oraclejdk8
      jdk: oraclejdk11

script:
  - mvn -Dmaven.javadoc.skip=true -e package -V
